#!/usr/bin/env php
<?php
$autoload = __DIR__.'/vendor/autoload.php';
if(!file_exists($autoload)){
 echo "[FRISBY]: Unable to initialize Frisby Console Component!".PHP_EOL
 .PHP_EOL."[FRISBY]: Updating composer...".PHP_EOL;
 shell_exec("composer update");
}
require_once $autoload;

use Frisby\Framework\CommandLine;
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$cli = CommandLine::getInstance();


$cli->newCommand('migrate')->description('This is a test command listener');

$cli->init($argv);