#!/usr/bin/env php
<?php
$autoload = __DIR__.'/vendor/autoload.php';
if(!file_exists($autoload)){
 echo "[FRISBY]: Unable to initialize Frisby Console Component!".PHP_EOL
 .PHP_EOL."[FRISBY]: Updating composer...".PHP_EOL;
 shell_exec("composer update");
}
require_once $autoload;

use Frisby\Framework\Migration;
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

if($argv[1] == "migrate"){
    $m = new Migration();
    $m->applyAllMigrations('up');
}

if($argv[1] == "rollback:all"){
    $m = new Migration();
    $m->applyAllMigrations('down');
}